. PIC-2289
ministryofjustice/court-hearing-event-receiver pull request #229
Opened 2022-07-21 10:40 UTC by vb-moj

2022-07-21 11:38 UTC, rschallapalli requested changes
Unit and integration tests need updating?

2022-07-25 07:48 UTC, rschallapalli requested changes

2022-07-25 09:58 UTC, jhevans approved these changes

2022-07-25 10:12 UTC, rschallapalli approved these changes

2022-07-25 10:12 UTC, merged